version: "3.9"
services:
    app:
        build:
            args:
                user: renamer
                uid: 1000
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: bank-accs-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - bank-accs

    nginx:
        image: nginx:alpine
        container_name: bank-accs-nginx
        ports:
            - '${FORWARD_APP_PORT:-80}:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - bank-accs

    db:
        image: mysql:5.7
        container_name: bank-accs-mysql
        command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password' ]
        tty: true
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
        driver: local

networks:
    bank-accs:
        driver: bridge
